apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-anywhere
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: model-anywhere
  template:
    metadata:
      labels:
        app: model-anywhere
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
