apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model-anywhere
  namespace: mlops
spec:
  predictor:
    containers:
      - name: predictor
        image: rohit1k/model-anywhere-mlops:latest
        ports:
          - containerPort: 3000
